"""Inventory management for mimirheim-reporter.

Maintains ``inventory.js`` in the report output directory. This file is a
JavaScript module that ``index.html`` loads at startup to build its report
table without requiring a running web server.

Format of ``inventory.js``::

    // Auto-generated by mimirheim-reporter. Do not edit manually.
    window.MIMIRHEIM_REPORTS = [
      {
        "ts": "2026-04-02T14:00:00Z",
        "file": "2026-04-02T14-00-00Z_report.html",
        "strategy": "minimize_cost",
        "solve_status": "optimal",
        ...
      }
    ];

Entries are sorted newest-first. All metric values are pre-computed so that
``index.html`` can render the table without additional JSON parsing.

What this module does not do:
- It does not write HTML report files.
- It does not subscribe to MQTT.
- It does not render Plotly charts.
"""
from __future__ import annotations

import json
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

_INVENTORY_FILENAME = "inventory.js"
_PREAMBLE = "// Auto-generated by mimirheim-reporter. Do not edit manually.\nwindow.MIMIRHEIM_REPORTS = "
_SUFFIX = ";\n"

# Keys extracted from a dump pair for one inventory entry.
_STEP_HOURS = 0.25  # 15 minutes


def _read_inventory(output_dir: Path) -> list[dict]:
    """Read the current ``inventory.js`` and return its entries list.

    Returns an empty list if the file does not exist or cannot be parsed.

    Args:
        output_dir: Directory containing ``inventory.js``.

    Returns:
        A list of inventory entry dicts, in whatever order they were stored.
    """
    path = output_dir / _INVENTORY_FILENAME
    if not path.exists():
        return []
    try:
        content = path.read_text()
        # Strip the JavaScript wrapper: "// comment...\nwindow.MIMIRHEIM_REPORTS = <json>;"
        json_start = content.find("[")
        json_end = content.rfind("]") + 1
        if json_start < 0 or json_end <= json_start:
            return []
        return json.loads(content[json_start:json_end])
    except (OSError, json.JSONDecodeError) as exc:
        logger.warning("Could not read %s: %s; starting fresh.", path, exc)
        return []


def _write_inventory(output_dir: Path, entries: list[dict]) -> None:
    """Write the entries list to ``inventory.js``, newest-first.

    Args:
        output_dir: Directory to write ``inventory.js`` into.
        entries: List of inventory entry dicts to write. Will be sorted
            newest-first by the ``ts`` field before writing.
    """
    sorted_entries = sorted(entries, key=lambda e: e.get("ts", ""), reverse=True)
    path = output_dir / _INVENTORY_FILENAME
    path.write_text(
        _PREAMBLE + json.dumps(sorted_entries, indent=2) + _SUFFIX
    )


def _build_entry(
    ts: str,
    report_file: str,
    inp: dict,
    out: dict,
) -> dict:
    """Build a single inventory entry dict from a dump pair.

    Args:
        ts: ISO 8601 timestamp string, e.g. ``"2026-04-02T14:00:00Z"``.
        report_file: Filename of the HTML report, e.g.
            ``"2026-04-02T14-00-00Z_report.html"``.
        inp: Parsed input dump JSON.
        out: Parsed output dump JSON.

    Returns:
        A dict with all pre-computed inventory metrics.
    """
    schedule = out.get("schedule", [])
    naive = out.get("naive_cost_eur") or 0.0
    optimised = out.get("optimised_cost_eur") or 0.0
    credit = out.get("soc_credit_eur") or 0.0
    effective = optimised - credit
    saving = naive - effective

    total_import_kwh = sum(
        s.get("grid_import_kw", 0.0) * _STEP_HOURS for s in schedule
    )
    total_export_kwh = sum(
        s.get("grid_export_kw", 0.0) * _STEP_HOURS for s in schedule
    )

    pv_total_kwh = sum(
        max(0.0, sp.get("kw", 0.0)) * _STEP_HOURS
        for s in schedule
        for sp in s.get("devices", {}).values()
        if sp.get("type") == "pv"
    )
    load_total_kwh = sum(
        max(0.0, -sp.get("kw", 0.0)) * _STEP_HOURS
        for s in schedule
        for sp in s.get("devices", {}).values()
        if sp.get("type") in ("static_load", "deferrable_load")
    )
    load_served_local = max(0.0, load_total_kwh - total_import_kwh)
    self_suf_pct = (
        round(load_served_local / load_total_kwh * 100.0, 1)
        if load_total_kwh > 0.0
        else 0.0
    )

    # Derive the dump filenames from the report filename. The stem before
    # "_report.html" is the safe_ts used for all three files in the dump pair.
    dump_base = report_file[: -len("_report.html")] if report_file.endswith("_report.html") else report_file

    return {
        "ts": ts,
        "file": report_file,
        "input_file": f"{dump_base}_input.json",
        "output_file": f"{dump_base}_output.json",
        "strategy": out.get("strategy", ""),
        "solve_status": out.get("solve_status", ""),
        "horizon_steps": len(schedule),
        "naive_cost_eur": round(naive, 4),
        "optimised_cost_eur": round(optimised, 4),
        "soc_credit_eur": round(credit, 4),
        "effective_cost_eur": round(effective, 4),
        "saving_eur": round(saving, 4),
        "dispatch_suppressed": bool(out.get("dispatch_suppressed", False)),
        "total_import_kwh": round(total_import_kwh, 3),
        "total_export_kwh": round(total_export_kwh, 3),
        "self_sufficiency_pct": self_suf_pct,
    }


def update(
    output_dir: Path,
    ts: str,
    report_file: str,
    inp: dict,
    out: dict,
) -> None:
    """Append or update one inventory entry and rewrite ``inventory.js``.

    If an entry with the same ``ts`` already exists it is replaced; otherwise
    the new entry is appended. The file is always rewritten sorted newest-first.

    Args:
        output_dir: Directory containing ``inventory.js``.
        ts: ISO 8601 timestamp for the new entry.
        report_file: Filename of the HTML report.
        inp: Parsed input dump JSON.
        out: Parsed output dump JSON.
    """
    entries = _read_inventory(output_dir)
    new_entry = _build_entry(ts, report_file, inp, out)
    # Remove any existing entry with the same ts.
    entries = [e for e in entries if e.get("ts") != ts]
    entries.append(new_entry)
    _write_inventory(output_dir, entries)


def remove(output_dir: Path, ts: str) -> None:
    """Remove an inventory entry by timestamp and rewrite ``inventory.js``.

    A no-op if no entry with the given ``ts`` exists.

    Args:
        output_dir: Directory containing ``inventory.js``.
        ts: ISO 8601 timestamp of the entry to remove.
    """
    entries = _read_inventory(output_dir)
    entries = [e for e in entries if e.get("ts") != ts]
    _write_inventory(output_dir, entries)


def _build_stub_entry(ts: str, report_file: str) -> dict:
    """Build a minimal inventory stub for a report whose dump pair is missing.

    The stub contains only the fields required for GC (``ts`` and ``file``).
    All metric values are absent so that the index page renders the row with
    clearly missing data rather than showing misleading zeros.

    Args:
        ts: ISO 8601 timestamp string.
        report_file: Filename of the HTML report.

    Returns:
        A dict with ``ts`` and ``file`` only.
    """
    return {"ts": ts, "file": report_file}


def rebuild_from_disk(output_dir: Path, dump_dir: Path) -> None:
    """Reconcile ``inventory.js`` with the HTML report files currently on disk.

    The HTML file is the ground truth: every ``*_report.html`` in
    ``output_dir`` must have exactly one inventory entry; entries whose HTML
    file no longer exists are removed.

    The reconciliation strategy for each on-disk HTML file:

    1. If ``inventory.js`` already contains a full entry for that timestamp,
       keep it as-is. This preserves metrics for reports whose dump pair has
       since been deleted by mimirheim's own dump rotation.
    2. If the entry is absent or is a stub (missing metric keys), and the
       dump pair exists in ``dump_dir``, build a full entry from the dump
       data.
    3. If neither a full entry nor a dump pair is available, keep or create a
       stub (``ts`` and ``file`` only) so GC can count the file and eventually
       remove it when it falls below the retention threshold.

    This is called at daemon startup to recover from a corrupted or deleted
    ``inventory.js`` and to process dump pairs that arrived while the daemon
    was offline. A restart never loses metrics for previously tracked reports.

    Args:
        output_dir: Directory containing ``*_report.html`` files.
        dump_dir: Directory containing the source dump JSON pairs.
    """
    # Build a lookup of the existing inventory, keyed by ts, so we can
    # preserve full entries that are already correct.
    existing: dict[str, dict] = {
        e["ts"]: e for e in _read_inventory(output_dir) if "ts" in e
    }

    report_files = sorted(output_dir.glob("*_report.html"))
    entries: list[dict] = []
    n_kept = 0
    n_built = 0
    n_stubs = 0

    for report_path in report_files:
        safe_ts = report_path.name[: -len("_report.html")]
        # Convert safe_ts (hyphens in time part) back to ISO format.
        # safe_ts looks like "2026-04-02T14-00-00Z"; canonical ts uses colons.
        if "T" in safe_ts:
            date_part, time_part = safe_ts.split("T", 1)
            ts = date_part + "T" + time_part.replace("-", ":", 2)
        else:
            ts = safe_ts

        # Case 1: existing full entry — keep it, preserving metrics even when
        # the dump pair has been deleted by mimirheim's dump rotation.
        existing_entry = existing.get(ts)
        if existing_entry and "naive_cost_eur" in existing_entry:
            entries.append(existing_entry)
            n_kept += 1
            continue

        # Case 2: entry missing or is a stub — try to build from the dump pair.
        input_path = dump_dir / f"{safe_ts}_input.json"
        output_path = dump_dir / f"{safe_ts}_output.json"
        if input_path.exists() and output_path.exists():
            try:
                inp = json.loads(input_path.read_text())
                out = json.loads(output_path.read_text())
                entries.append(_build_entry(ts, report_path.name, inp, out))
                n_built += 1
                continue
            except (OSError, json.JSONDecodeError) as exc:
                logger.warning(
                    "Could not read dump pair for %s: %s; retaining stub.", safe_ts, exc
                )

        # Case 3: no full entry and no readable dump pair — keep or create stub.
        if existing_entry:
            entries.append(existing_entry)
        else:
            logger.warning(
                "No inventory entry and no dump pair for %s; creating stub so "
                "GC can count this report.",
                safe_ts,
            )
            entries.append(_build_stub_entry(ts, report_path.name))
        n_stubs += 1

    _write_inventory(output_dir, entries)
    logger.info(
        "Inventory reconciled: %d kept, %d built from dump, %d stub(s); "
        "%d report(s) total in %s.",
        n_kept,
        n_built,
        n_stubs,
        len(entries),
        output_dir,
    )
