"""Unit tests for reporter.inventory.

Covers update(), remove(), and rebuild_from_disk() in isolation using
temporary directories. No MQTT or daemon infrastructure is needed.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from reporter import inventory as inv


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_TS1 = "2026-04-02T14:00:00Z"
_TS2 = "2026-04-02T14:15:00Z"
_TS3 = "2026-04-02T14:30:00Z"


def _minimal_out(strategy: str = "minimize_cost") -> dict:
    return {
        "strategy": strategy,
        "solve_status": "optimal",
        "naive_cost_eur": 1.0,
        "optimised_cost_eur": 0.8,
        "soc_credit_eur": 0.05,
        "dispatch_suppressed": False,
        "schedule": [
            {"grid_import_kw": 2.0, "grid_export_kw": 0.0, "devices": {}},
            {"grid_import_kw": 1.5, "grid_export_kw": 0.0, "devices": {}},
        ],
    }


def _minimal_inp() -> dict:
    return {"prices": []}


# ---------------------------------------------------------------------------
# update()
# ---------------------------------------------------------------------------

def test_update_creates_inventory_js(tmp_path: Path) -> None:
    """update() must create inventory.js if it does not yet exist."""
    inv.update(tmp_path, _TS1, "2026-04-02T14-00-00Z_report.html", _minimal_inp(), _minimal_out())
    assert (tmp_path / "inventory.js").exists()


def test_update_inventory_js_starts_with_preamble(tmp_path: Path) -> None:
    """inventory.js must start with the JavaScript wrapper comment."""
    inv.update(tmp_path, _TS1, "2026-04-02T14-00-00Z_report.html", _minimal_inp(), _minimal_out())
    content = (tmp_path / "inventory.js").read_text()
    assert content.startswith("// Auto-generated by mimirheim-reporter")


def test_update_appends_entry(tmp_path: Path) -> None:
    """Adding two different timestamps must produce two entries."""
    inv.update(tmp_path, _TS1, "ts1_report.html", _minimal_inp(), _minimal_out())
    inv.update(tmp_path, _TS2, "ts2_report.html", _minimal_inp(), _minimal_out())
    entries = inv._read_inventory(tmp_path)
    assert len(entries) == 2


def test_update_sorted_newest_first(tmp_path: Path) -> None:
    """Entries must be ordered newest-first (descending by ts)."""
    inv.update(tmp_path, _TS1, "ts1_report.html", _minimal_inp(), _minimal_out())
    inv.update(tmp_path, _TS3, "ts3_report.html", _minimal_inp(), _minimal_out())
    inv.update(tmp_path, _TS2, "ts2_report.html", _minimal_inp(), _minimal_out())
    entries = inv._read_inventory(tmp_path)
    tss = [e["ts"] for e in entries]
    assert tss == sorted(tss, reverse=True)


def test_update_replaces_duplicate_ts(tmp_path: Path) -> None:
    """Calling update() twice with the same ts must not create duplicate entries."""
    inv.update(tmp_path, _TS1, "ts1_report.html", _minimal_inp(), _minimal_out("minimize_cost"))
    inv.update(tmp_path, _TS1, "ts1_report_v2.html", _minimal_inp(), _minimal_out("zero_export"))
    entries = inv._read_inventory(tmp_path)
    assert len(entries) == 1
    assert entries[0]["strategy"] == "zero_export"


def test_update_entry_has_expected_keys(tmp_path: Path) -> None:
    """A freshly written entry must contain all expected inventory keys."""
    inv.update(tmp_path, _TS1, "ts1_report.html", _minimal_inp(), _minimal_out())
    entries = inv._read_inventory(tmp_path)
    entry = entries[0]
    required_keys = {
        "ts", "file", "strategy", "solve_status", "horizon_steps",
        "naive_cost_eur", "optimised_cost_eur", "soc_credit_eur",
        "effective_cost_eur", "saving_eur", "dispatch_suppressed",
        "total_import_kwh", "total_export_kwh", "self_sufficiency_pct",
    }
    assert required_keys <= set(entry.keys())


# ---------------------------------------------------------------------------
# remove()
# ---------------------------------------------------------------------------

def test_remove_deletes_entry(tmp_path: Path) -> None:
    """remove() must delete the matching entry and leave others intact."""
    inv.update(tmp_path, _TS1, "ts1_report.html", _minimal_inp(), _minimal_out())
    inv.update(tmp_path, _TS2, "ts2_report.html", _minimal_inp(), _minimal_out())
    inv.remove(tmp_path, _TS1)
    entries = inv._read_inventory(tmp_path)
    assert len(entries) == 1
    assert entries[0]["ts"] == _TS2


def test_remove_noop_on_missing_ts(tmp_path: Path) -> None:
    """remove() must be a no-op when the ts is not present."""
    inv.update(tmp_path, _TS1, "ts1_report.html", _minimal_inp(), _minimal_out())
    inv.remove(tmp_path, "2999-01-01T00:00:00Z")  # does not exist
    entries = inv._read_inventory(tmp_path)
    assert len(entries) == 1


# ---------------------------------------------------------------------------
# rebuild_from_disk()
# ---------------------------------------------------------------------------

def test_rebuild_from_disk_empty_dir(tmp_path: Path) -> None:
    """rebuild_from_disk() on an empty output_dir must produce an empty inventory."""
    inv.rebuild_from_disk(tmp_path, tmp_path)
    entries = inv._read_inventory(tmp_path)
    assert entries == []


def test_rebuild_from_disk_picks_up_report(tmp_path: Path) -> None:
    """rebuild_from_disk() must create an entry for every dump pair with a report file."""
    # The safe_ts format as used in filenames: hyphens replace colons in the time part.
    safe_ts = "2026-04-02T14-00-00Z"
    ts = "2026-04-02T14:00:00Z"
    report_file = f"{safe_ts}_report.html"
    # Write dummy report HTML
    (tmp_path / report_file).write_text("<html></html>")
    # Write dump pair
    dump_dir = tmp_path / "dumps"
    dump_dir.mkdir()
    (dump_dir / f"{safe_ts}_input.json").write_text(json.dumps(_minimal_inp()))
    (dump_dir / f"{safe_ts}_output.json").write_text(json.dumps(_minimal_out()))

    inv.rebuild_from_disk(tmp_path, dump_dir)
    entries = inv._read_inventory(tmp_path)
    assert len(entries) == 1
    assert entries[0]["ts"] == ts
    assert entries[0]["file"] == report_file


def test_rebuild_from_disk_stub_entry_for_missing_dump(tmp_path: Path) -> None:
    """rebuild_from_disk() must add a stub entry for a report with no prior inventory
    entry and no dump pair.  The stub ensures GC can count and eventually
    remove the file; without it, orphaned reports accumulate forever.
    """
    safe_ts = "2026-04-02T14-00-00Z"
    ts = "2026-04-02T14:00:00Z"
    report_file = f"{safe_ts}_report.html"
    (tmp_path / report_file).write_text("<html></html>")
    dump_dir = tmp_path / "dumps"
    dump_dir.mkdir()
    # No prior inventory.js and no dump pair files.
    inv.rebuild_from_disk(tmp_path, dump_dir)
    entries = inv._read_inventory(tmp_path)
    assert len(entries) == 1
    assert entries[0]["ts"] == ts
    assert entries[0]["file"] == report_file
    # Stub entry must not contain metric keys (no dump data to compute them from).
    assert "naive_cost_eur" not in entries[0]


def test_rebuild_from_disk_preserves_existing_entry_when_dump_gone(tmp_path: Path) -> None:
    """rebuild_from_disk() must keep an existing full inventory entry even when
    the corresponding dump pair has been deleted.

    This is the core restart resilience guarantee: metrics must not be lost
    just because mimirheim rotated away the source dump files.
    """
    safe_ts = "2026-04-02T14-00-00Z"
    ts = "2026-04-02T14:00:00Z"
    report_file = f"{safe_ts}_report.html"
    dump_dir = tmp_path / "dumps"
    dump_dir.mkdir()

    # First pass: report + dump pair both present → full entry written.
    (tmp_path / report_file).write_text("<html></html>")
    (dump_dir / f"{safe_ts}_input.json").write_text(json.dumps(_minimal_inp()))
    (dump_dir / f"{safe_ts}_output.json").write_text(json.dumps(_minimal_out()))
    inv.rebuild_from_disk(tmp_path, dump_dir)

    # Delete the dump pair, simulating mimirheim dump rotation.
    (dump_dir / f"{safe_ts}_input.json").unlink()
    (dump_dir / f"{safe_ts}_output.json").unlink()

    # Second pass (restart): entry must be preserved from inventory.js.
    inv.rebuild_from_disk(tmp_path, dump_dir)
    entries = inv._read_inventory(tmp_path)
    assert len(entries) == 1
    assert entries[0]["ts"] == ts
    # Full metrics must still be present.
    assert "naive_cost_eur" in entries[0]


def test_rebuild_from_disk_removes_entry_for_deleted_html(tmp_path: Path) -> None:
    """rebuild_from_disk() must remove entries whose HTML file no longer exists."""
    safe_ts = "2026-04-02T14-00-00Z"
    ts = "2026-04-02T14:00:00Z"
    report_file = f"{safe_ts}_report.html"
    dump_dir = tmp_path / "dumps"
    dump_dir.mkdir()

    # Create a full entry.
    (tmp_path / report_file).write_text("<html></html>")
    (dump_dir / f"{safe_ts}_input.json").write_text(json.dumps(_minimal_inp()))
    (dump_dir / f"{safe_ts}_output.json").write_text(json.dumps(_minimal_out()))
    inv.rebuild_from_disk(tmp_path, dump_dir)
    assert len(inv._read_inventory(tmp_path)) == 1

    # GC deletes the HTML; reconcile should remove the entry.
    (tmp_path / report_file).unlink()
    inv.rebuild_from_disk(tmp_path, dump_dir)
    assert inv._read_inventory(tmp_path) == []


def test_rebuild_from_disk_stub_is_gc_visible(tmp_path: Path) -> None:
    """A stub entry must be counted by gc.collect() so the orphaned file is removed."""
    from reporter import gc as reporter_gc

    safe_ts = "2026-04-02T14-00-00Z"
    report_file = f"{safe_ts}_report.html"
    html_path = tmp_path / report_file
    html_path.write_text("<html></html>")
    dump_dir = tmp_path / "dumps"
    dump_dir.mkdir()

    inv.rebuild_from_disk(tmp_path, dump_dir)
    # One report on disk, max_reports=0 means collect nothing.
    reporter_gc.collect(tmp_path, max_reports=0)
    assert html_path.exists()
    # max_reports=1 is already satisfied; still no deletion.
    reporter_gc.collect(tmp_path, max_reports=1)
    assert html_path.exists()

    # Add a second (newer) stub so the first is the oldest.
    safe_ts2 = "2026-04-03T14-00-00Z"
    report_file2 = f"{safe_ts2}_report.html"
    html_path2 = tmp_path / report_file2
    html_path2.write_text("<html></html>")
    inv.rebuild_from_disk(tmp_path, dump_dir)

    # max_reports=1: oldest (safe_ts) must be deleted.
    reporter_gc.collect(tmp_path, max_reports=1)
    assert not html_path.exists()
    assert html_path2.exists()
