name: Create release image and push to GHCR

on:
  release:
    types: [published]
    tags:
      - "v*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  BUILD_NAME: Mimirheim
  BUILD_DESCRIPTION: MILP energy optimiser for home battery, PV, and EV scheduling against dynamic electricity prices.
  BUILD_ARCH: amd64, aarch64
  BUILD_VERSION: edge
  BUILD_DATE: ${{ github.event.head_commit.timestamp }}
  BUILD_REF: ${{ github.sha }}
  
jobs:
  build-and-push-image:
    name: Create edge image and push to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1

      - name: Setup Buildkit
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4
        with:
          platforms: linux/amd64,linux/arm64

      - name: GHCR Login
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=raw,value=stable
          labels: |
            io.hass.name="${{ env.BUILD_NAME }}" \
            io.hass.description="${{ env.BUILD_DESCRIPTION }}" \
            io.hass.arch="${{ env.BUILD_ARCH }}" \
            io.hass.type="addon" \
            io.hass.version="${{ env.BUILD_VERSION }}" \
            org.opencontainers.image.title="${{ env.BUILD_NAME }}" \
            org.opencontainers.image.description="${{ env.BUILD_DESCRIPTION }}" \
            org.opencontainers.image.created="${{ env.BUILD_DATE }}" \
            org.opencontainers.image.revision="${{ env.BUILD_REF }}" \
            org.opencontainers.image.source="https://github.com/jsimonetti/mimirheim" \
            org.opencontainers.image.version="${{ env.BUILD_VERSION }}"

      - name: Build and Push
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7
        with:
          push: true
          platforms: linux/arm64,linux/amd64
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          context: .
          file: container/Dockerfile
