name: GHCR Cleanup

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:


jobs:
  ghcr-cleanup-image:
    name: ghcr cleanup actions
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@d52806a0dc70b430571a37da1fde39733ffd640f # v1.2.2
        with:
          keep-n-tagged: 20
          exclude-tags: edge,stable,buildcache,pr-*
          keep-n-untagged: 20
          delete-partial-images: true
          delete-ghost-images: true
          delete-orphaned-images: true